// <auto-generated />
using System;
using CommunityCenterTracker.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunityCenterTracker.Migrations
{
    [DbContext(typeof(CommunityCenterContext))]
    [Migration("20230902220405_CreatesDTOs")]
    partial class CreatesDTOs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunityCenterTracker.Model.Bundle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Bundles");
                });

            modelBuilder.Entity("CommunityCenterTracker.Model.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BundleId")
                        .HasColumnType("integer");

                    b.Property<int>("DaysToGrow")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Seasons")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BundleId");

                    b.ToTable("Crop");
                });

            modelBuilder.Entity("CommunityCenterTracker.Model.Fish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BundleId")
                        .HasColumnType("integer");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Seasons")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Times")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BundleId");

                    b.ToTable("Fish");
                });

            modelBuilder.Entity("CommunityCenterTracker.Model.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("CommunityCenterTracker.Model.Bundle", b =>
                {
                    b.HasOne("CommunityCenterTracker.Model.Section", "Section")
                        .WithMany("Bundles")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("CommunityCenterTracker.Model.Crop", b =>
                {
                    b.HasOne("CommunityCenterTracker.Model.Bundle", null)
                        .WithMany("Crops")
                        .HasForeignKey("BundleId");
                });

            modelBuilder.Entity("CommunityCenterTracker.Model.Fish", b =>
                {
                    b.HasOne("CommunityCenterTracker.Model.Bundle", null)
                        .WithMany("Fishes")
                        .HasForeignKey("BundleId");
                });

            modelBuilder.Entity("CommunityCenterTracker.Model.Bundle", b =>
                {
                    b.Navigation("Crops");

                    b.Navigation("Fishes");
                });

            modelBuilder.Entity("CommunityCenterTracker.Model.Section", b =>
                {
                    b.Navigation("Bundles");
                });
#pragma warning restore 612, 618
        }
    }
}
